import { NextResponse } from "next/server";
import crypto from "crypto";

export const runtime = "nodejs";

const DEFAULT_ENV = "prod3";

function getFilenameFromUrl(url: string) {
  try {
    const u = new URL(url);
    const name = u.pathname.split("/").pop();
    return name && name.includes(".") ? name : "generated-image.png";
  } catch {
    return "generated-image.png";
  }
}

function parseList(value?: string | null) {
  if (!value) return [];
  return value
    .split(",")
    .map((v) => v.trim())
    .filter(Boolean);
}

export async function POST(req: Request) {
  const token = process.env.SPRINKLR_BEARER_TOKEN;
  const apiKey = process.env.SPRINKLR_API_KEY;
  const env = process.env.SPRINKLR_ENV || DEFAULT_ENV;

  if (!token || !apiKey) {
    return NextResponse.json({ error: "Missing Sprinklr credentials" }, { status: 500 });
  }

  const body = await req.json().catch(() => ({}));
  const imageUrl = String(body?.imageUrl || "").trim();
  const name = String(body?.name || "Generated Image").trim() || "Generated Image";
  const description = String(body?.description || "Generated by BFL").trim();

  if (!imageUrl) return NextResponse.json({ error: "imageUrl is required" }, { status: 400 });

  const uploadTrackerId = `gen_${crypto.randomUUID()}`;

  let imgResp: Response;
  try {
    imgResp = await fetch(imageUrl);
  } catch (e: any) {
    return NextResponse.json({ error: "Failed to fetch generated image", details: e?.message || "Unknown error" }, { status: 500 });
  }

  if (!imgResp.ok) {
    const txt = await imgResp.text();
    return NextResponse.json({ error: `Image fetch failed: ${imgResp.status}`, details: txt }, { status: 500 });
  }

  const arrayBuf = await imgResp.arrayBuffer();
  const contentType = imgResp.headers.get("content-type") || "image/png";
  const filename = getFilenameFromUrl(imageUrl);

  const form = new FormData();
  form.append("file", new Blob([arrayBuf], { type: contentType }), filename);

  const uploadUrl = `https://api3.sprinklr.com/${env}/api/v1/sam/upload?contentType=IMAGE&uploadTrackerId=${encodeURIComponent(
    uploadTrackerId
  )}`;

  const uploadResp = await fetch(uploadUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      key: apiKey,
      Accept: "application/json",
    },
    body: form,
  });

  if (!uploadResp.ok) {
    const txt = await uploadResp.text();
    return NextResponse.json({ error: `Sprinklr upload failed: ${uploadResp.status}`, details: txt }, { status: 500 });
  }

  const uploadData = await uploadResp.json();
  const uploadedContentId = uploadData?.id;

  if (!uploadedContentId) {
    return NextResponse.json({ error: "Upload succeeded but no id returned", uploadData }, { status: 500 });
  }

  const assetStatus = (process.env.SPRINKLR_ASSET_STATUS || "DRAFT").toUpperCase();
  const assetSource = process.env.SPRINKLR_ASSET_SOURCE || "SPRINKLR";
  const shareLevel = (process.env.SPRINKLR_SHARE_LEVEL || "GLOBAL").toUpperCase();
  const shareWithIds = parseList(process.env.SPRINKLR_SHARE_WITH_IDS);
  const campaignIds = parseList(process.env.SPRINKLR_CAMPAIGN_IDS);
  const tags = parseList(process.env.SPRINKLR_TAGS);

  const now = Date.now();
  const availableAfterTime = Number(process.env.SPRINKLR_AVAILABLE_AFTER_TIME || now);
  const expiryTime = Number(process.env.SPRINKLR_EXPIRY_TIME || 2208988800000);

  const customFieldTarget = process.env.SPRINKLR_CUSTOM_FIELDS_TARGET || "clientCustomProperties";
  const customFields = {
    _c_6985fd71c7447f30fed52c73: ["final"],
    c_6985fd14c7447f30fed3e65d: ["123"],
  } as Record<string, string[]>;

  const shareConfig: any = { shareLevel };
  if (shareWithIds.length) shareConfig.sharedWithIds = shareWithIds;

  const payload: any = {
    name,
    description,
    assetType: "PHOTO",
    assetStatus,
    uploadedContentId,
    availableAfterTime,
    expiryTime,
    shareConfigs: [shareConfig],
    assetSource,
  };

  if (tags.length) payload.tags = tags;
  if (campaignIds.length) payload.campaignIds = campaignIds;

  if (customFieldTarget === "partnerCustomFields") payload.partnerCustomFields = customFields;
  else payload.clientCustomProperties = customFields;

  const createResp = await fetch(`https://api3.sprinklr.com/${env}/api/v1/sam`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Key: apiKey,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!createResp.ok) {
    const txt = await createResp.text();
    return NextResponse.json(
      { error: `Sprinklr asset create failed: ${createResp.status}`, details: txt, uploadedContentId },
      { status: 500 }
    );
  }

  const createData = await createResp.json();
  return NextResponse.json(
    {
      uploadedContentId,
      asset: createData,
    },
    { status: 200 }
  );
}
