import { NextResponse } from "next/server";
import crypto from "crypto";
import { getSprinklrBearerToken } from "@/lib/lib/sprinklr-auth";

export const runtime = "nodejs";

const DEFAULT_ENV = "prod3";

function parseList(value?: string | null) {
  if (!value) return [];
  return value
    .split(",")
    .map((v) => v.trim())
    .filter(Boolean);
}

export async function POST(req: Request) {
  //const token = process.env.SPRINKLR_BEARER_TOKEN;
  const apiKey = process.env.SPRINKLR_API_KEY;
  const env = process.env.SPRINKLR_ENV || DEFAULT_ENV;

  // if (!token || !apiKey) {
  //   return NextResponse.json({ error: "Missing Sprinklr credentials" }, { status: 500 });
  // }
  if (!apiKey) {
    return NextResponse.json({ error: "Missing SPRINKLR_API_KEY" }, { status: 500 });
  }

  let token: string;
  try {
    token = await getSprinklrBearerToken();
  } catch (e: unknown) {
    const details = e instanceof Error ? e.message : "Unknown error";
    return NextResponse.json({ error: "Failed to load Sprinklr token", details }, { status: 500 });
  }

  const body = await req.json().catch(() => ({}));
  const imageUrl = String(body?.imageUrl || "").trim();
  const name = String(body?.name || "Generated Image").trim() || "Generated Image";
  const description = String(body?.description || "Generated by BFL").trim();

  if (!imageUrl) return NextResponse.json({ error: "imageUrl is required" }, { status: 400 });

  const uploadTrackerId = `gen_${crypto.randomUUID()}`;

  const importUrl = `https://api3.sprinklr.com/${env}/api/v1/sam/importUrl?importType=IMAGE&url=${encodeURIComponent(
    imageUrl
  )}&uploadTrackerId=${encodeURIComponent(uploadTrackerId)}`;

  const importResp = await fetch(importUrl, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Key: apiKey,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
  });

  if (!importResp.ok) {
    const txt = await importResp.text();
    return NextResponse.json({ error: `Sprinklr import failed: ${importResp.status}`, details: txt }, { status: 500 });
  }

  const importData = await importResp.json();
  const uploadedContentId = importData?.data?.id || importData?.id;

  if (!uploadedContentId) {
    return NextResponse.json({ error: "Import succeeded but no id returned", importData }, { status: 500 });
  }

  const assetStatus = (process.env.SPRINKLR_ASSET_STATUS || "DRAFT").toUpperCase();
  const assetSource = process.env.SPRINKLR_ASSET_SOURCE || "SPRINKLR";
  const shareLevel = (process.env.SPRINKLR_SHARE_LEVEL || "GLOBAL").toUpperCase();
  const shareWithIds = parseList(process.env.SPRINKLR_SHARE_WITH_IDS);
  const campaignIds = parseList(process.env.SPRINKLR_CAMPAIGN_IDS);
  const tags = parseList(process.env.SPRINKLR_TAGS);

  const now = Date.now();
  const availableAfterTime = Number(process.env.SPRINKLR_AVAILABLE_AFTER_TIME || now);
  const expiryTime = Number(process.env.SPRINKLR_EXPIRY_TIME || 2208988800000);

  const customFields = {
    _c_6985fd14c7447f30fed3e65d: ["123"],
    _c_6985fd71c7447f30fed52c73: ["Final Product"],
  } as Record<string, string[]>;

  const shareConfig: any = { shareLevel };
  if (shareWithIds.length) shareConfig.sharedWithIds = shareWithIds;

  const payload: any = {
    name,
    description,
    assetType: "PHOTO",
    assetStatus,
    uploadedContentId,
    availableAfterTime,
    expiryTime,
    shareConfigs: [shareConfig],
    assetSource,
  };

  if (tags.length) payload.tags = tags;
  if (campaignIds.length) payload.campaignIds = campaignIds;

  const createResp = await fetch(`https://api3.sprinklr.com/${env}/api/v1/sam`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Key: apiKey,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!createResp.ok) {
    const txt = await createResp.text();
    return NextResponse.json(
      { error: `Sprinklr asset create failed: ${createResp.status}`, details: txt, uploadedContentId },
      { status: 500 }
    );
  }

  const createData = await createResp.json();
  const createdAsset = Array.isArray(createData) ? createData[0] : createData;
  const assetId = createdAsset?.id || createdAsset?.data?.id || createdAsset?.asset?.id;

  if (!assetId) {
    return NextResponse.json(
      { error: "Asset create succeeded but no asset id returned", uploadedContentId, asset: createData },
      { status: 500 }
    );
  }

  const updatePayload = {
    clientCustomProperties: customFields,
    partnerCustomFields: customFields,
  };

  await new Promise((resolve) => setTimeout(resolve, 3000));

  const updateResp = await fetch(`https://api3.sprinklr.com/${env}/api/v1/sam/${assetId}`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${token}`,
      Key: apiKey,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(updatePayload),
  });

  const updateText = await updateResp.text();
  const updateData = updateText ? JSON.parse(updateText) : {};

  if (!updateResp.ok) {
    return NextResponse.json(
      {
        error: `Sprinklr asset update failed: ${updateResp.status}`,
        details: updateText,
        uploadedContentId,
        assetId,
      },
      { status: 500 }
    );
  }

  return NextResponse.json(
    {
      uploadedContentId,
      assetId,
      asset: createData,
      updateStatus: updateResp.status,
      update: updateData,
      updateRaw: updateText,
    },
    { status: 200 }
  );
}
